#!/bin/bash

export NODE_OPTIONS="--no-warnings"

if command -v bunx &>/dev/null; then
    bunx lint-staged
elif command -v pnpx &>/dev/null; then
    pnpx lint-staged
elif command -v npx &>/dev/null; then
    npx lint-staged
else
    echo "THERE WAS AN ERROR!"
    exit 1
fi