name: Publish Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7
            - name: Set up Go
              uses: actions/setup-go@v7
              with:
                  go-version-file: go.mod
            - name: Generate Templ Code
              run: make generate
            - name: Build Project
              run: make
            - name: Create Release
              if: github.actor != 'nektos/act'
              uses: softprops/action-gh-release@v3
              with:
                  name: Release
                  tag_name: release
                  files: bin/*
                  fail_on_unmatched_files: true
